spring.datasource.url=jdbc:postgresql://localhost:5432/test39
spring.datasource.username=test_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Actuator
management.endpoints.web.exposure.include=mappings,beans,caches,env,metrics,shutdown,auditevents,threaddump
management.endpoint.env.show-values=always